services:

  # banco de dados
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PHP - Laravel
  backend:
    build: ./backend
    networks:
      - app-network
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    working_dir: /var/www
    command: |
      bash -c "
        composer install --no-dev --optimize-autoloader &&
        php artisan migrate && 
        php artisan serve --host=0.0.0.0 --port=8000
      "

  # Node - React
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: